//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int ArticuloID { get; set; }
        public string Descripcion { get; set; }
        public string Modelo { get; set; }
        public double Precio { get; set; }
        public int Existencia { get; set; }
    }
}
